steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile
      - --target
      - api
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/geoissue-api:$BUILD_ID
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/geoissue-api:$BUILD_ID

substitutions:
  _REGION: europe-west3
  _REPOSITORY: geoissue
