import "dotenv/config";
import { neon } from "@neondatabase/serverless";
import { Issue, Report, ReportInput, Status } from "./domain.js";

export const sql = process.env.DATABASE_URL ? neon(process.env.DATABASE_URL) : null;
const seededAt = new Date().toISOString();
export const memory = { users: new Map<string, { uid: string; email: string; name: string; role: "user" | "admin" }>(), issues: [
  { id: "demo-road", title: "Damaged road surface", description: "A deep pothole needs attention near the junction.", category: "Road", status: "in_progress", priority: "high", latitude: 39.9334, longitude: 32.8597, reportCount: 14, createdAt: seededAt, history: [{ status: "submitted", changedAt: seededAt }] },
  { id: "demo-water", title: "Leaking water line", description: "Water is collecting on the pavement beside the park.", category: "Water", status: "in_review", priority: "normal", latitude: 39.9381, longitude: 32.8522, reportCount: 7, createdAt: seededAt, history: [{ status: "submitted", changedAt: seededAt }] },
  { id: "demo-lamp", title: "Street lights out", description: "Two lights have been out since last week.", category: "Electricity", status: "submitted", priority: "normal", latitude: 39.9271, longitude: 32.8691, reportCount: 3, createdAt: seededAt, history: [{ status: "submitted", changedAt: seededAt }] },
] as Issue[], reports: [] as Report[], supporters: new Set<string>() };
export const store = {
  async issues() { return sql ? (await sql`SELECT id::text, title, description, category, status, priority, latitude, longitude, report_count AS "reportCount", created_at AS "createdAt" FROM issues ORDER BY created_at DESC`) as Issue[] : memory.issues; },
  async issue(id: string) { const rows = sql ? await sql`SELECT id::text, title, description, category, status, priority, latitude, longitude, report_count AS "reportCount", created_at AS "createdAt" FROM issues WHERE id = ${id}` : memory.issues.filter((x) => x.id === id); return rows[0] as Issue | undefined; },
  async reports(uid: string) { return sql ? await sql`SELECT id::text, issue_id::text AS "issueId", title, description, category, latitude, longitude, created_at AS "createdAt" FROM reports WHERE reporter_id = ${uid} ORDER BY created_at DESC` : memory.reports.filter((x) => x.reporterId === uid); },
  async user(uid: string) { return memory.users.get(uid); },
  async users() { return sql ? await sql`SELECT user_id AS uid, email, name, role FROM users ORDER BY created_at DESC` : [...memory.users.values()]; },
  async saveUser(user: { uid: string; email: string; name: string; role: "user" | "admin" }) { memory.users.set(user.uid, user); return user; },
  async createReport(input: { report: Omit<Report, "issueId">; issue: Issue; existing?: Issue }) {
    if (!sql) { const issue = input.existing ?? input.issue; if (!input.existing) memory.issues.unshift(issue); memory.reports.unshift({ ...input.report, issueId: issue.id }); issue.reportCount += 1; return { issue, report: { ...input.report, issueId: issue.id } }; }
    const rows = await sql`INSERT INTO reports (issue_id, reporter_id, title, description, category, latitude, longitude) VALUES (${input.existing?.id ?? input.issue.id}, ${input.report.reporterId}, ${input.report.title}, ${input.report.description}, ${input.report.category}, ${input.report.latitude}, ${input.report.longitude}) RETURNING id::text, issue_id::text AS "issueId", title, description, category, latitude, longitude, created_at AS "createdAt"`;
    await sql`UPDATE issues SET report_count = report_count + 1 WHERE id = ${input.existing?.id ?? input.issue.id}`;
    return { issue: await this.issue(input.existing?.id ?? input.issue.id), report: rows[0] };
  },
  async updateStatus(id: string, status: Status, uid: string, note = "") { if (!sql) { const issue = memory.issues.find((x) => x.id === id); if (issue) { issue.status = status; issue.history.push({ status, changedAt: new Date().toISOString(), note }); } return issue; } const rows = await sql`UPDATE issues SET status = ${status}, updated_at = NOW() WHERE id = ${id} RETURNING id::text, title, description, category, status, priority, latitude, longitude, report_count AS "reportCount", created_at AS "createdAt"`; await sql`INSERT INTO issue_status_history (issue_id, status, changed_by, note) VALUES (${id}, ${status}, ${uid}, ${note})`; return rows[0]; },
  async updateReport(id: string, uid: string, data: Partial<ReportInput>) { if (!sql) { const report = memory.reports.find((x) => x.id === id && x.reporterId === uid); if (!report) return null; Object.assign(report, data); return report; } const rows = await sql`UPDATE reports SET title = COALESCE(${data.title ?? null}, title), description = COALESCE(${data.description ?? null}, description), category = COALESCE(${data.category ?? null}, category), latitude = COALESCE(${data.latitude ?? null}, latitude), longitude = COALESCE(${data.longitude ?? null}, longitude) WHERE id = ${id} AND reporter_id = ${uid} RETURNING id::text, issue_id::text AS "issueId", title, description, category, latitude, longitude, created_at AS "createdAt"`; return rows[0]; },
  async deleteReport(id: string, uid: string) { if (!sql) { const index = memory.reports.findIndex((x) => x.id === id && x.reporterId === uid); if (index < 0) return null; return memory.reports.splice(index, 1)[0]; } const rows = await sql`DELETE FROM reports WHERE id = ${id} AND reporter_id = ${uid} RETURNING id`; return rows[0]; },
  async support(issueId: string, uid: string, enabled: boolean) { if (!sql) { const key = `${issueId}:${uid}`; enabled ? memory.supporters.add(key) : memory.supporters.delete(key); return { supported: enabled }; } if (enabled) await sql`INSERT INTO issue_supporters (issue_id, user_id) VALUES (${issueId}, ${uid}) ON CONFLICT DO NOTHING`; else await sql`DELETE FROM issue_supporters WHERE issue_id = ${issueId} AND user_id = ${uid}`; return { supported: enabled }; },
  async setPriority(id: string, priority: "low" | "normal" | "high") { if (!sql) { const issue = memory.issues.find((x) => x.id === id); if (issue) issue.priority = priority; return issue; } const rows = await sql`UPDATE issues SET priority = ${priority}, updated_at = NOW() WHERE id = ${id} RETURNING id::text, title, description, category, status, priority, latitude, longitude, report_count AS "reportCount", created_at AS "createdAt"`; return rows[0]; },
};
